spring.application.name=backend
waqi.token=9923aa8cfcfc539c9d07b91ea


spring.datasource.url=jdbc:mysql://localhost:3306/air_quality?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
